language: c++
deploy:
  provider: releases
  api_key:
    secure: >
      0HIS6srOsKsti3klaZ0XyADQZrXJJ/QQ8GO8sRQA2gmPaWB+7anEzN1kpuus7F2
      Tqg0O3F3txh/nmdpAtJJFgIp60yDBjllwf9FYKwLofU7aP5FIWYkYIlJ2x1OFO8
      7X+Dyoc5iNv/mDcmRVGbcCCHXz5RcLmUIBfwlGCE3ubc7i/4Kma+Ei0gJgoWVVt
      N+h1s47EEqYPVDv5rKbL39Hki013EjFSl4JEjSts9oksL2fQsBFgcTA3SXTIxGN
      SfVh6lZrO1JC8VLHwo1dwdZ7rbepE9xxYf/c1A2bVs6Hi3q0BTrkI4aecHoDwf3
      4GARB+T6816mhOMM9HKlCpMSrLrbiit/kTVQjcL9GeHwEukjullHWpUEFD1nelD
      cR3Dz9vk7YSc9ERk9Yg+GhFHrLYmZ0HpLnwsAsUL1Zc6ZlzWzoBCdy6sa8YDoVo
      eWN559khUwVnHDh2xmGQfb8IXMYa+EsaniaU+V7bAcQdbyYNpC8J4pm4Qowhnfq
      sWC8Jiu8zEC0y5aDnrXbxZeUvSFslX8L0DUQAoBW1egiUOHqAKXBEyZmkHeJ3Nc
      O0piaePyfA80VqdnLB40LFxt+0hFkwsRc1aLqAWEr8F/e3N/54Sz0niOB7Ww6p5
      UAldJGGhUguL6vkjiyHKqBq45MzJJ/k/E4gNn2yG3Pvu19CxPugMs=
  file: $DEPLOY_FILE
  skip_cleanup: true
  on:
    tags: true

before_install:
  - if [[ -z "$DOCKER_IMAGE" ]]; then
      brew update ;
    else
      docker pull "$DOCKER_IMAGE" &&
      docker run -dit -v "$(pwd)":/home/launcher --name launcher "$DOCKER_IMAGE" &&
      docker exec launcher apt-get update ;
    fi
install:
  - if [[ -z "$DOCKER_IMAGE" ]]; then
      brew install p7zip &&
      PATH="$(./qt5-mac.sh . base tools):$PATH" ;
    else
      docker exec launcher apt-get install --no-install-recommends -y 
        build-essential qt5-default qt5-qmake qtbase5-dev-tools zlib1g-dev ;
    fi
script:
  - if [[ -z "$DOCKER_IMAGE" ]]; then
      qmake $QMAKE_ARGS && make ;
    else
      docker exec -w /home/launcher launcher qmake &&
      docker exec -w /home/launcher launcher make ;
    fi
after_script:
  - if [[ -n "$DOCKER_IMAGE" ]]; then docker stop launcher; fi
before_deploy:
  - if [[ -z "$DOCKER_IMAGE" ]]; then
      macdeployqt OpenRCT2.app &&
      zip -ryq "$DEPLOY_FILE" OpenRCT2.app ;
    else
      tar -czf "$DEPLOY_FILE" OpenRCT2 ;
    fi

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env:
        - DEPLOY_FILE=OpenRCT2Launcher-macos.zip
    - os: linux
      dist: xenial
      services: docker
      env:
        - DEPLOY_FILE=OpenRCT2Launcher-Linux-x64.tar.gz
        - DOCKER_IMAGE=amd64/ubuntu:bionic
    - os: linux
      dist: xenial
      services: docker
      env:
        - DEPLOY_FILE=OpenRCT2Launcher-Linux-x86.tar.gz
        - DOCKER_IMAGE=i386/ubuntu:bionic

