version: 0.0.4#{build}
os: Visual Studio 2013
install:
- cmd: >-
    SET PATH=%PATH%;C:\Qt\5.5\msvc2013\bin

    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd.bat"
build_script:
- cmd: >-
    qmake

    nmake

    mkdir build-Windows

    copy release\OpenRCT2.exe build-Windows\OpenRCT2.exe

    windeployqt build-Windows\OpenRCT2.exe

    choco install innosetup

    set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

    iscc installer.iss
artifacts:
- path: build-Windows/*
  name: zip-archive
- path: OpenRCT2Launcher-win.exe
  name: exe-installer
deploy:
- provider: GitHub
  auth_token:
    secure: miPrvp4kj2bjSwLYaxsKk3X48RwA+dCdTXYd6MfZ2E5xvBhq/3EzsrUhIbAE1cS+
  artifact: zip-archive, exe-installer
  on:
    appveyor_repo_tag: true